name: Build

on:
  workflow_call:
    inputs:
      version:
        description: Version to build
        required: true
        type: string

env:
  JAVA_DISTRIBUTION: zulu
  JAVA_VERSION: 21

jobs:
  unit-test:
    runs-on: [ ubuntu-latest ]
    steps:
      - run: echo "==jobs/steps=="
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}
      - uses: actions/setup-java@v4
        with:
          cache: gradle
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - run: ./gradlew clean test spotlessCheck --exclude-task :chucknorris-integration-test:test

      # Add a build step to create artifacts
      - name: Build with Gradle
        run: ./gradlew build --exclude-task test
      
      # Upload the build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chuck-api-build
          path: |
            **/build/libs/*.jar
            **/build/distributions/*.zip
  
  # integration-test:
  #   runs-on: [ ubuntu-latest ]
  #   steps:
  #     - run: echo "==integration-test/steps=="
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: ${{ inputs.version }}
  #     - uses: actions/setup-java@v4
  #       with:
  #         cache: gradle
  #         distribution: ${{ env.JAVA_DISTRIBUTION }}
  #         java-version: ${{ env.JAVA_VERSION }}
  #     - name: Run Integration Test
  #       shell: bash
  #       run: ./chucknorris-integration-test/script/run-integration-test.sh
